/*
BASE VARIABLES UI
*/
export const SWITCH_HOME_TAB = 'SWITCH_HOME_TAB';
export const SWITCH_SIGNUP = 'SWITCH_SIGNUP';
export const SWITCH_LOGIN = 'SWITCH_LOGIN';

/*
USER
*/
export const USER_IS_LOGGED = 'USER_IS_LOGGED';
export const USER_NAME = 'USER_NAME';
export const USER_NEED_VALIDATION = 'USER_NEED_VALIDATION';
/*
EDITOR
*/
export const EDITOR_SCALE= 'EDITOR_SCALE';
export const EDITOR_OBJECT_SELECTED='EDITOR_OBJECT_SELECTED';
export const EDITOR_OBJECT_EDIT='EDITOR_OBJECT_EDIT';
export const EDITOR_ADD = 'EDITOR_ADD';
export const CHANGE_TOPBAR = 'CHANGE_TOPBAR';
/*
 FORMS 
 */
export const SIGNIN_FORM_CHANGE = 'SIGNIN_FORM_CHANGE';
export const SIGNIN_FORM_CLEAR = 'SIGNIN_FORM_CLEAR';
export const LOGIN_FORM_CHANGE= 'LOGIN_FORM_CHANGE';
export const LOGIN_FORM_CLEAR = 'LOGIN_FORM_CLEAR';
/*
NOTIFICATIONS
*/
export const SET_ERRORS_MSG = 'SET_ERRORS_MSG';
export const CLEAR_ERROS_MSG = 'CLEAR_ERRORS_MSG';
export const SET_SUCCESS_MSG = 'SET_SUCCESS_MSG';
export const CLEAR_SUCCESS_MSG = 'CLEAR_SUCCESS_MSG';
/*
LOADING
*/
export const SWITCH_LOADING = 'SWITCH_LOADING';